baseURL = "https://www.cluemasters.es/"
languageCode = "es"
title = "ClueMasters | Blog de Escape Rooms y Juegos de Mesa"
theme = "PaperMod"
uglyURLs = false
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

[permalinks]
  posts = "/posts/:slug/"

[params]
  description = "Reseñas y comparativas de juegos de mesa y escape rooms, artículos para juagadores, makers y game maasters"
  keywords = ["escape room", "kits", "juegos de mesa", "review", "blog", "reseñas", "juegos en casa", "scape rooms"]
  author = "ClueMasters"
  favicon = "/clue-masters.ico"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  showtoc = true
  tocopen = true
  disableThemeToggle = false
  env = "production"

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Artículos"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Quiénes somos"
    url = "/quienes-somos/"
    weight = 3

  [[menu.main]]
    name = "Productos"
    url = "/productos/"
    weight = 4

  [[menu.main]]
    name = "Política de privacidad"
    url = "/politica-de-privacidad/"
    weight = 5

  [[menu.main]]
    name = "Términos y condiciones"
    url = "/terminos-y-condiciones/"
    weight = 6

  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 7

  [[menu.main]]
    name = "Tienda"
    url = "https://www.etsy.com/shop/ClueMasters"
    weight = 8